### ISSUE TITLE
Directory Authentication Error: wpDirAuth config error: No directory server available for authentication.

### ISSUE THREAD

**Issue by ShwetaEmploysure** [edb-gjengen/wpdirauth#1]
Hello Plugin Author,

Can you please suggest for the below error?

**Directory Authentication Error: wpDirAuth config error: No directory server available for authentication.**

I get the the above error when tried to login through the wordpress admin panel.

I am currently working on the localhost having path as http://localhost/testsite/ 

**Any video tutorial or explained document for the plugin will be very helpful.**

WordPress Settings:
**************************
Enable Directory Authentication? Yes
Require SSL Login? No
Automatically Register Authenticated Users? No
Enable SSL Connectivity? No SSL Connectivity
Directory Servers (Domain Controllers) ? localhost/testsite/
Account Filter : shweta.mukta
Account Suffix : @employsure.com.au
Base DN : empty (Not sure what to fill in)
Bind DN : empty (Not sure what to fill in)
Bind Password : my selected password
Authentication Groups: empty
Institution Name: Employsure
Marketing name for Institutional Single-Sign-On ID : empty
Login Screen Message: Employsure members can login directly using their institutional password.
Password Change Message: To change a Employsure password, please refer to the official institutional password policy.
Terms of Services Agreement: No

**Comment by nikolaik** [comment]
Hi @ShwetaEmploysure, This is not the right place to ask about this plugin. You should read on https://wordpress.org/plugins/wpdirauth/installation/ and ask in https://wordpress.org/support/plugin/wpdirauth if you have any questions.
